name: elfc
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  dartz: ^0.10.1
  get: ^4.6.5
  google_fonts: ^3.0.1
  flare_flutter: ^3.0.2
  flutter_keyboard_visibility: ^5.4.0
  flutter_screenutil: ^5.6.0
  flutter_svg: ^1.1.6
  font_awesome_flutter: ^10.3.0
  package_info_plus: ^3.0.2
  rxdart: ^0.27.7
  cupertino_icons: ^1.0.2
  flutter_secure_storage: ^8.0.0
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  faker: ^2.0.0
  mockito: ^5.0.11
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/google_fonts/
    - assets/icons/
    - assets/images/
